
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobProcessor.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DeviceData
{

    public int Id { get; set; }

    public string DeviceId { get; set; }

    public System.DateTime SendDateTime { get; set; }

    public decimal Temperature { get; set; }

    public decimal Humidity { get; set; }

    public decimal PM25 { get; set; }

}

}
